version: '3.8'

services:
  sensor_simulation:
    build:
      context: ./sensor_simulation
    container_name: sensor_simulation
    volumes:
      - ./shared_data:/shared_data
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./shared_data:/shared_data
      - ./custom_grafana.ini:/etc/grafana/grafana.ini  # Mount the custom configuration
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    restart: always
    privileged: true  # Enables privileged mode

volumes:
  grafana_data:
