version: '3.8'

services:

  pms5003:
    build:
      context: ./pms5003
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
    container_name: pms5003
    restart: always
    depends_on:
      - mqtt-broker  # Ensure MySQL starts before pms5003
    devices:
      - "/dev/ttyS0:/dev/ttyS0"

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always

  influxdb:
    image: arm64v8/influxdb:1.8  # Für Raspberry Pi (ARM-Architektur)!
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensor_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - mqtt-broker
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: always
    privileged: true  # Enables privileged mode (not reccomended for production)

volumes:
  influxdb:
  grafana_data: