version: '3.8'

services:

  pms5003:
    build:
      context: ./pms5003
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: pms5003
    restart: always
    depends_on:
      - mysql  # Ensure MySQL starts before pms5003
    devices:
      - "/dev/ttyS0:/dev/ttyS0"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: always
    privileged: true  # Enables privileged mode (not reccomended for production)

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # Persist MySQL data to local directory
    restart: always

volumes:
  grafana_data:
  mysql_data: