version: '3.8'

services:
  sensor_simulation:
    build:
      context: ./sensor_simulation
    container_name: sensor_simulation
    volumes:
      - ./shared_data:/shared_data
    restart: always
    depends_on:
      - mysql  # Ensure MySQL starts before sensor_simulation

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./shared_data:/shared_data
      - ./custom_grafana.ini:/etc/grafana/grafana.ini  # Mount the custom configuration
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    restart: always
    privileged: true  # Enables privileged mode

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: machichdannmal
      MYSQL_DATABASE: sensor_data
      MYSQL_USER: your_user
      MYSQL_PASSWORD: machichdannmal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data
    restart: always

volumes:
  grafana_data:
  mysql_data: