version: '3.8'

services:

  co2_sensor:
    build:
      context: ./co2_sensor
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    container_name: co2_sensor
    restart: always
    depends_on:
      - mqtt-broker
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  pms5003:
    build:
      context: ./pms5003
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    container_name: pms5003
    restart: always
    depends_on:
      - mqtt-broker
    devices:
      - "/dev/ttyS0:/dev/ttyS0"

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always

  influxdb:
    image: arm64v8/influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always

  telegraf:
    build:
      context: ./telegraf
    container_name: telegraf
    depends_on:
      - mqtt-broker
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: always
    privileged: true

volumes:
  influxdb:
  grafana_data:
